import waffleImg from './img/image-waffle-desktop.jpg'
import cremeBruleeImg from './img/image-creme-brulee-desktop.jpg'
import macaronImg from './img/image-macaron-desktop.jpg'
import tiramisuImg from './img/image-tiramisu-desktop.jpg'
import baklavaImg from './img/image-baklava-desktop.jpg'
import pieImg from './img/image-meringue-desktop.jpg'
import cakeImg from './img/image-cake-desktop.jpg'
import brownieImg from './img/image-brownie-desktop.jpg'
import pannaCottaImg from './img/image-panna-cotta-desktop.jpg'

export const menu = [
  {
  id: 1,
  category: 'Waffle',
  name: 'Waffle with Berries',
  description: 'A crisp, golden waffle served with fresh strawberries and a light dusting of powdered sugar.',
  price: '6.50',
  calories: 420,
  protein: 8,
  fat: 18,
  carbs: 58,
  image: waffleImg,
},
{
  id: 2,
  category: 'Crème Brûlée',
  name: 'Vanilla Bean Crème Brûlée',
  description: 'Classic French vanilla custard with a rich caramelized sugar crust.',
  price: '7.00',
  calories: 360,
  protein: 6,
  fat: 27,
  carbs: 25,
  image: cremeBruleeImg,
},
{
  id: 3,
  category: 'Macaron',
  name: 'Macaron Mix of Five',
  description: 'A colorful assortment of five delicate almond macarons with assorted fillings.',
  price: '8.00',
  calories: 480,
  protein: 8,
  fat: 22,
  carbs: 64,
  image: macaronImg,
},
{
  id: 4,
  category: 'Tiramisu',
  name: 'Classic Tiramisu',
  description: 'Layers of espresso-soaked ladyfingers with mascarpone cream and cocoa.',
  price: '5.50',
  calories: 430,
  protein: 7,
  fat: 28,
  carbs: 36,
  image: tiramisuImg,
},
{
  id: 5,
  category: 'Baklava',
  name: 'Pistachio Baklava',
  description: 'Flaky filo pastry layered with pistachios and finished with sweet honey syrup.',
  price: '4.00',
  calories: 350,
  protein: 6,
  fat: 20,
  carbs: 40,
  image: baklavaImg,
},
{
  id: 6,
  category: 'Pie',
  name: 'Lemon Meringue Pie',
  description: 'Tangy lemon filling topped with fluffy toasted meringue in a buttery crust.',
  price: '5.00',
  calories: 390,
  protein: 5,
  fat: 14,
  carbs: 61,
  image: pieImg,
},
{
  id: 7,
  category: 'Cake',
  name: 'Red Velvet Cake',
  description: 'Moist red velvet sponge layered with smooth cream cheese frosting.',
  price: '4.50',
  calories: 450,
  protein: 6,
  fat: 24,
  carbs: 54,
  image: cakeImg,
},
{
  id: 8,
  category: 'Brownie',
  name: 'Salted Caramel Brownie',
  description: 'Rich chocolate brownie topped with gooey salted caramel and sea salt flakes.',
  price: '5.50',
  calories: 470,
  protein: 6,
  fat: 26,
  carbs: 56,
  image: brownieImg,
},
{
  id: 9,
  category: 'Panna Cotta',
  name: 'Vanilla Panna Cotta',
  description: 'Silky smooth vanilla panna cotta served with a fresh berry compote.',
  price: '6.50',
  calories: 310,
  protein: 5,
  fat: 22,
  carbs: 23,
  image: pannaCottaImg,
},
]

export default menu